CREATE SEQUENCE SEQ_ID_USUARIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE TB_USUARIO(
    ID_USUARIO INTEGER DEFAULT SEQ_ID_USUARIO.nextval NOT NULL,
    NOME            VARCHAR2(100) NOT NULL,
    SENHA           VARCHAR2(60) NOT NULL,
    EMAIL           VARCHAR2(255) UNIQUE NOT NULL,
    ROLE            VARCHAR2(50) DEFAULT 'USER'
);